### ISSUE TITLE
Public imagery

### ISSUE THREAD

**Issue by guylepage3** [abbottsbury/abbottsbury#1]
> **Last updated**: Mar 27, 2024

**Description**
Public imagery for GitHub.

**Tasks**
- [x] Create and close issue.

**Reference(s)**
- [x] [Simple Icons](https://simpleicons.org/)
- [x] [Simpleicons.Vercel.App](https://simpleicons.vercel.app/)

**Comment by guylepage3** [comment]
```
github-lepage-banner-1600x170-light
width="100%"
https://github.com/abbottsbury/abbottsbury/assets/1711854/6a542fa9-fe1f-49e8-bb67-b5679182aeb7
```
<img src="https://github.com/abbottsbury/abbottsbury/assets/1711854/6a542fa9-fe1f-49e8-bb67-b5679182aeb7" width="100%" alt="Abbottsbury banner [abbottsbury-github-banner-1600x170-light]">

```
github-lepage-banner-1600x170-dark
width="100%"
https://github.com/abbottsbury/abbottsbury/assets/1711854/a5df8a46-fff5-42d3-9832-d16eb5c0251a
```
<img src="https://github.com/abbottsbury/abbottsbury/assets/1711854/a5df8a46-fff5-42d3-9832-d16eb5c0251a" width="100%" alt="Abbottsbury banner [abbottsbury-github-banner-1600x170-dark]">
